### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by Playz01** [Bigtruck2/AutoBridge#1]
hello sir , 
im writing this to let you know that im still using this plugin and i you can give me your discord to contact i have a custom skywars plugin but the old developer never answer now so if you can refactor the skywars plugin for me (i only have jar file) the version i have it has a problem i cant start the game.  i know you will say there is a lot of skywars plugin out but i have special features i have tried to search but never found

**Comment by Bigtruck2** [comment]
My discord tag is bigtruck2
